variable "prefix" {}
variable "AWS_CLUSTER_NAME" {}
variable "AWS_ACCESS_KEY_ID" {}
variable "AWS_SECRET_ACCESS_KEY" {}
variable "vpc_cidr_block" {}
variable retention_days {}
variable "desired_size" {}
variable "max_size" {}
variable "min_size" {}
variable "node_group_number" {}
variable "aws_instance_types" {}
